#!/usr/bin/env bun
import { chmodSync, mkdirSync, readdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { isIP } from "node:net";
import { dirname, join, resolve } from "node:path";
import { stdin, stdout } from "node:process";
import { createInterface } from "node:readline/promises";
import { fileURLToPath } from "node:url";
import { buildServeHttpUrl, createTailscaleServeClient } from "@muximo/infrastructure/cli-client";
import { isLoopbackOrPrivateBindHost, parseDotEnv, resolveProfileName } from "@muximo/profile";

export type ProfileConnection = "tailscale" | "lan" | "localhost";
export type ProfileClient = "browser" | "capacitor" | "none";
export type ProfileSchemaMode = "migrate" | "push";

export type ProfileSetupInput = {
  profileName: string;
  templateName: string;
  templateContents: string;
  connection: ProfileConnection;
  client: ProfileClient;
  schemaMode: ProfileSchemaMode;
  iosLocal: boolean;
  hostname?: string;
  lanHost?: string;
};

export type ProfileSetupPlan = {
  profileName: string;
  templateName: string;
  connection: ProfileConnection;
  client: ProfileClient;
  webOrigin?: string;
  profileContents: string;
  iosContents?: string;
};

export type ProfileTemplate = {
  name: string;
  path: string;
  contents: string;
};

export type ProfileSetupResult = {
  profilePath: string;
  iosPath?: string;
  webOrigin?: string;
};

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const templateFilePattern = /^\.env\.([A-Za-z0-9][A-Za-z0-9._-]*)\.example$/u;
const generatedProfileHeader = "# Generated by `mise profile`; rerun it to replace this file.";

function requireName(value: string): string {
  const name = resolveProfileName(value);
  if (name === undefined) throw new Error("a profile name is required");
  return name;
}

function requireGeneratedProfileName(value: string): string {
  const name = requireName(value);
  if (name === "example" || name.endsWith(".example")) {
    throw new Error("profile names reserved for .env.*.example recipes cannot be generated");
  }
  return name;
}

export function discoverProfileTemplates(root = repositoryRoot): ProfileTemplate[] {
  return readdirSync(root, { withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => {
      const match = templateFilePattern.exec(entry.name);
      if (!match) return undefined;
      const path = join(root, entry.name);
      return { name: match[1], path, contents: readFileSync(path, "utf8") };
    })
    .filter((template): template is ProfileTemplate => template !== undefined)
    .sort((left, right) => left.name.localeCompare(right.name));
}

export function createProfileSetupPlan(input: ProfileSetupInput): ProfileSetupPlan {
  const profileName = requireGeneratedProfileName(input.profileName);
  const templateName = requireName(input.templateName);
  const values = parseDotEnv(input.templateContents, `.env.${templateName}.example`);
  const webPort = readOptionalPort(values, "MUXIMO_WEB_PORT");
  const webServePort = readOptionalPort(values, "MUXIMO_WEB_SERVE_PORT");
  if ((webPort === undefined) !== (webServePort === undefined)) {
    throw new Error("profile recipe must define both MUXIMO_WEB_PORT and MUXIMO_WEB_SERVE_PORT");
  }
  const recipeWebConfiguration =
    webPort !== undefined && webServePort !== undefined ? { port: webPort, servePort: webServePort } : undefined;
  const webConfiguration = input.client === "none" ? undefined : recipeWebConfiguration;
  if (input.client === "browser" && webConfiguration === undefined) {
    throw new Error("a browser client requires Web ports in the selected profile recipe");
  }
  if (input.iosLocal && input.client !== "capacitor") {
    throw new Error("iOS Local configuration requires a capacitor client");
  }
  if (input.iosLocal && webConfiguration === undefined) {
    throw new Error("iOS Local configuration requires Web ports in the selected profile recipe");
  }

  const origins = webConfiguration
    ? [`http://127.0.0.1:${webConfiguration.port}`, `http://localhost:${webConfiguration.port}`]
    : [];
  const updates: Record<string, string> = {
    MUXIMO_SCHEMA_MODE: input.schemaMode,
  };
  const removeKeys = new Set([
    "MUXIMO_TAILSCALE_HOSTNAME",
    "MUXIMO_MUXIMOD_HOST",
    "MUXIMO_WEB_HOST",
    ...(webConfiguration === undefined || input.client === "none"
      ? ["MUXIMO_WEB_PORT", "MUXIMO_WEB_SERVE_PORT", "VITE_DEV_HOST", "VITE_DEV_PORT", "MUXIMOD_ALLOWED_ORIGINS"]
      : []),
  ]);
  let webOrigin: string | undefined;

  if (input.connection === "tailscale") {
    if (!input.hostname?.trim()) throw new Error("a Tailscale hostname is required");
    const hostnameUrl = new URL(buildServeHttpUrl(input.hostname, webConfiguration?.servePort ?? 443));
    const hostname = stripIpv6Brackets(hostnameUrl.hostname);
    updates.MUXIMO_TAILSCALE_HOSTNAME = hostname;
    const publicUrl = webConfiguration
      ? new URL(buildServeHttpUrl(input.hostname, webConfiguration.servePort))
      : undefined;
    if (publicUrl) {
      webOrigin = publicUrl.origin;
      origins.push(webOrigin);
    }
  } else if (input.connection === "lan") {
    const lanHost = input.lanHost?.trim();
    if (!lanHost || !isLanHost(lanHost)) {
      throw new Error("LAN connection requires a private IP address");
    }
    updates.MUXIMO_MUXIMOD_HOST = lanHost;
    if (webConfiguration) {
      updates.MUXIMO_WEB_HOST = lanHost;
      webOrigin = buildHttpOrigin(lanHost, webConfiguration.port);
      origins.push(webOrigin);
    }
  } else {
    if (webConfiguration) webOrigin = `http://127.0.0.1:${webConfiguration.port}`;
  }

  if (origins.length > 0) updates.MUXIMOD_ALLOWED_ORIGINS = unique(origins).join(",");
  const profileContents = renderProfileContents({
    templateName,
    templateContents: input.templateContents,
    updates,
    removeKeys: [...removeKeys],
  });

  return {
    profileName,
    templateName,
    connection: input.connection,
    client: input.client,
    ...(webOrigin === undefined ? {} : { webOrigin }),
    profileContents,
    ...(input.iosLocal && webOrigin !== undefined ? { iosContents: renderIosConfig(webOrigin) } : {}),
  };
}

export function renderProfileContents(input: {
  templateName: string;
  templateContents: string;
  updates: Readonly<Record<string, string>>;
  removeKeys?: readonly string[];
}): string {
  const removeKeys = new Set(input.removeKeys ?? []);
  const remaining = new Set(Object.keys(input.updates));
  const lines = input.templateContents.replace(/\r\n?/gu, "\n").split("\n");
  const rendered: string[] = [];

  for (const line of lines) {
    const match = /^(\s*(?:export\s+)?)([A-Za-z_][A-Za-z0-9_]*)(\s*=\s*).*$/u.exec(line);
    if (!match) {
      rendered.push(line);
      continue;
    }
    const key = match[2];
    if (removeKeys.has(key)) continue;
    const value = input.updates[key];
    if (value === undefined) {
      rendered.push(line);
      continue;
    }
    rendered.push(`${match[1]}${key}=${encodeDotEnvValue(value)}`);
    remaining.delete(key);
  }

  while (rendered.at(-1) === "") rendered.pop();
  if (remaining.size > 0) {
    if (rendered.length > 0) rendered.push("");
    for (const key of Object.keys(input.updates)) {
      if (remaining.has(key)) rendered.push(`${key}=${encodeDotEnvValue(input.updates[key])}`);
    }
  }

  const recipeHeader = [
    generatedProfileHeader,
    `# Source recipe: .env.${requireName(input.templateName)}.example`,
  ].join("\n");
  return `${recipeHeader}\n${rendered.join("\n")}\n`;
}

export function renderIosConfig(webOrigin: string): string {
  const url = new URL(webOrigin);
  const scheme = url.protocol.slice(0, -1);
  const port = url.port || (scheme === "https" ? "443" : "80");
  const host = stripIpv6Brackets(url.hostname);
  return [
    "// Generated by `mise profile`; rerun it to replace this file.",
    `MUXIMO_WEB_SCHEME = ${scheme}`,
    `MUXIMO_WEB_HOST = ${host}`,
    `MUXIMO_WEB_PORT = ${port}`,
    "",
  ].join("\n");
}

async function runInteractiveProfileSetup(): Promise<ProfileSetupResult> {
  const templates = discoverProfileTemplates();
  if (templates.length === 0) throw new Error("no .env.<name>.example profile recipes were found");

  const prompt = createInterface({ input: stdin, output: stdout });
  try {
    const profileName = requireGeneratedProfileName(await askRequired(prompt, "Profile name"));
    const defaultTemplate = templates.some((template) => template.name === profileName)
      ? profileName
      : templates[0].name;
    const templateName = await askChoice(
      prompt,
      "Base profile recipe",
      templates.map((template) => template.name),
      defaultTemplate,
    );
    const template = templates.find((candidate) => candidate.name === templateName);
    if (!template) throw new Error(`profile recipe not found: ${templateName}`);
    const templateValues = parseDotEnv(template.contents, template.path);
    const hasWebRecipe =
      templateValues.MUXIMO_WEB_PORT !== undefined || templateValues.MUXIMO_WEB_SERVE_PORT !== undefined;
    const defaultClient = hasWebRecipe ? "browser" : "none";
    const client = await askChoice(prompt, "Client runtime", ["browser", "capacitor", "none"] as const, defaultClient);
    const connection = await askChoice(
      prompt,
      "Connection method",
      ["tailscale", "lan", "localhost"] as const,
      "tailscale",
    );

    let hostname: string | undefined;
    let lanHost: string | undefined;
    if (connection === "tailscale") {
      const detectedHostname = await detectTailscaleHostname();
      hostname = await askRequired(prompt, "Tailscale hostname", detectedHostname);
    } else if (connection === "lan") {
      lanHost = await askRequired(prompt, "LAN private IP address");
    }

    const iosLocal =
      client === "capacitor" && hasWebRecipe
        ? await askBoolean(prompt, "Generate apps/web/ios/local.xcconfig", true)
        : false;
    const defaultSchemaMode = templateValues.MUXIMO_SCHEMA_MODE === "push" ? "push" : "migrate";
    const schemaMode = await askChoice(prompt, "Schema mode", ["migrate", "push"] as const, defaultSchemaMode);
    const plan = createProfileSetupPlan({
      profileName,
      templateName,
      templateContents: template.contents,
      connection,
      client,
      schemaMode,
      iosLocal,
      ...(hostname === undefined ? {} : { hostname }),
      ...(lanHost === undefined ? {} : { lanHost }),
    });

    const profilePath = join(repositoryRoot, `.env.${plan.profileName}`);
    writeGeneratedFile(profilePath, plan.profileContents);
    let iosPath: string | undefined;
    if (plan.iosContents !== undefined) {
      iosPath = join(repositoryRoot, "apps", "web", "ios", "local.xcconfig");
      writeGeneratedFile(iosPath, plan.iosContents);
    }
    stdout.write(`[profile] wrote ${profilePath}\n`);
    if (iosPath) stdout.write(`[profile] wrote ${iosPath}\n`);
    if (plan.client === "capacitor") {
      if (plan.webOrigin) {
        stdout.write(`[profile] Capacitor Local Web origin: ${plan.webOrigin}\n`);
      } else {
        stdout.write("[profile] Capacitor origin: capacitor://localhost (provided by muximod)\n");
      }
    } else if (plan.webOrigin) {
      stdout.write(`[profile] Web origin: ${plan.webOrigin}\n`);
    } else {
      stdout.write("[profile] No Web client origin configured\n");
    }
    return { profilePath, ...(iosPath === undefined ? {} : { iosPath }), webOrigin: plan.webOrigin };
  } finally {
    prompt.close();
  }
}

async function askRequired(
  prompt: ReturnType<typeof createInterface>,
  question: string,
  defaultValue?: string,
): Promise<string> {
  while (true) {
    const value = (await prompt.question(`${question}${defaultValue ? ` [${defaultValue}]` : ""}: `)).trim();
    const resolved = value || defaultValue;
    if (resolved) return resolved;
    stdout.write("A value is required.\n");
  }
}

async function askChoice<T extends string>(
  prompt: ReturnType<typeof createInterface>,
  question: string,
  choices: readonly T[],
  defaultValue: T,
): Promise<T> {
  while (true) {
    const answer = (await prompt.question(`${question} (${choices.join("/")}) [${defaultValue}]: `))
      .trim()
      .toLowerCase();
    const value = answer || defaultValue;
    if (choices.includes(value as T)) return value as T;
    stdout.write(`Choose one of: ${choices.join(", ")}.\n`);
  }
}

async function askBoolean(
  prompt: ReturnType<typeof createInterface>,
  question: string,
  defaultValue: boolean,
): Promise<boolean> {
  const defaultLabel = defaultValue ? "Y/n" : "y/N";
  while (true) {
    const answer = (await prompt.question(`${question}? (${defaultLabel}) `)).trim().toLowerCase();
    if (!answer) return defaultValue;
    if (["y", "yes"].includes(answer)) return true;
    if (["n", "no"].includes(answer)) return false;
    stdout.write("Answer yes or no.\n");
  }
}

async function detectTailscaleHostname(): Promise<string | undefined> {
  try {
    return await createTailscaleServeClient({ environment: process.env }).resolveHostname();
  } catch (error) {
    stdout.write(`[profile] could not detect Tailscale hostname: ${errorMessage(error)}\n`);
    return undefined;
  }
}

function writeGeneratedFile(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  const temporaryPath = `${path}.tmp-${process.pid}`;
  try {
    writeFileSync(temporaryPath, contents, { mode: 0o600 });
    chmodSync(temporaryPath, 0o600);
    renameSync(temporaryPath, path);
    chmodSync(path, 0o600);
  } catch (error) {
    removeTemporaryFile(temporaryPath);
    throw error;
  }
  removeTemporaryFile(temporaryPath);
}

function removeTemporaryFile(path: string): void {
  try {
    unlinkSync(path);
  } catch (error) {
    if (!isErrorCode(error, "ENOENT")) throw error;
  }
}

function readOptionalPort(values: Record<string, string>, key: string): number | undefined {
  const value = values[key]?.trim();
  if (!value) return undefined;
  const port = Number(value);
  if (!Number.isInteger(port) || port < 1 || port > 65_535) {
    throw new Error(`profile recipe must define ${key} as a port`);
  }
  return port;
}

function buildHttpOrigin(host: string, port: number): string {
  const urlHost = host.includes(":") && !host.startsWith("[") ? `[${host}]` : host;
  return new URL(`http://${urlHost}:${port}`).origin;
}

function isLanHost(value: string): boolean {
  const version = isIP(value);
  if (version === 0 || !isLoopbackOrPrivateBindHost(value)) return false;
  return !isLoopbackAddress(value);
}

function isLoopbackAddress(value: string): boolean {
  return value === "::1" || value.startsWith("127.");
}

function stripIpv6Brackets(value: string): string {
  return value.startsWith("[") && value.endsWith("]") ? value.slice(1, -1) : value;
}

function unique(values: readonly string[]): string[] {
  return [...new Set(values)];
}

function encodeDotEnvValue(value: string): string {
  return /^[A-Za-z0-9_./:,-]+$/u.test(value) ? value : JSON.stringify(value);
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function isErrorCode(error: unknown, code: string): boolean {
  return error instanceof Error && "code" in error && error.code === code;
}

if (import.meta.main) {
  try {
    const argumentsForSetup = process.argv.slice(2);
    if (argumentsForSetup.length > 0) {
      throw new Error(`profile setup does not accept arguments: ${argumentsForSetup.join(" ")}`);
    }
    await runInteractiveProfileSetup();
  } catch (error) {
    process.stderr.write(`[profile] error: ${errorMessage(error)}\n`);
    process.exitCode = 1;
  }
}
