import { describe, it } from "bun:test";
import { strict as assert } from "node:assert";
import {
  type Assertion,
  hasError,
  hasObserved,
  noFixture,
  type OperationCase,
  type OperationTable,
  runOperationTable,
  type TestRegistrar,
} from "@muximo/test-support";
import { createProfileSetupPlan, type ProfileSetupInput, type ProfileSetupPlan } from "./profile.ts";

type ProfileContext = {
  webOrigin: string | null;
  profileContents: string | null;
  iosContents: string | null;
};

const localRecipe = [
  "# recipe comment",
  "MUXIMO_SCHEMA_MODE=migrate",
  "MUXIMO_WEB_PORT=5227",
  "MUXIMO_WEB_SERVE_PORT=8449",
  "MUXIMO_TAILSCALE_HOSTNAME=old.tailnet.ts.net",
  "MUXIMO_MUXIMOD_HOST=192.168.50.10",
  "MUXIMO_WEB_HOST=192.168.50.10",
  "EXTRA_VALUE=kept",
  "",
].join("\n");

const stagingRecipe = ["MUXIMO_SCHEMA_MODE=migrate", ""].join("\n");

function profileContains(expected: RegExp): Assertion<ProfileContext, ProfileSetupPlan> {
  return {
    name: `profile contains ${expected}`,
    check: (context, result) => {
      assert.equal(result.ok, true);
      assert.match(context.profileContents ?? "", expected);
    },
  };
}

function profileOmits(expected: RegExp): Assertion<ProfileContext, ProfileSetupPlan> {
  return {
    name: `profile omits ${expected}`,
    check: (context, result) => {
      assert.equal(result.ok, true);
      assert.doesNotMatch(context.profileContents ?? "", expected);
    },
  };
}

const cases = [
  {
    name: "rewrites a Tailscale push profile and its local iOS URL",
    input: {
      profileName: "dev",
      templateName: "local",
      templateContents: localRecipe,
      connection: "tailscale",
      client: "capacitor",
      schemaMode: "push",
      iosLocal: true,
      hostname: "machine.tailnet.ts.net",
    },
    assert: [
      hasObserved<ProfileContext, ProfileSetupPlan>("webOrigin", "https://machine.tailnet.ts.net:8449"),
      profileContains(/MUXIMO_SCHEMA_MODE=push/u),
      profileContains(/MUXIMO_TAILSCALE_HOSTNAME=machine\.tailnet\.ts\.net/u),
      profileContains(
        /MUXIMOD_ALLOWED_ORIGINS=http:\/\/127\.0\.0\.1:5227,http:\/\/localhost:5227,https:\/\/machine\.tailnet\.ts\.net:8449/u,
      ),
      profileContains(/EXTRA_VALUE=kept/u),
      profileOmits(/MUXIMO_MUXIMOD_HOST=/u),
      profileOmits(/MUXIMO_WEB_HOST=/u),
      hasObserved<ProfileContext, ProfileSetupPlan>(
        "iosContents",
        "// Generated by `mise profile`; rerun it to replace this file.\n" +
          "MUXIMO_WEB_SCHEME = https\n" +
          "MUXIMO_WEB_HOST = machine.tailnet.ts.net\n" +
          "MUXIMO_WEB_PORT = 8449\n",
      ),
    ],
  },
  {
    name: "rewrites a private LAN migration profile",
    input: {
      profileName: "lan-office",
      templateName: "local",
      templateContents: localRecipe,
      connection: "lan",
      client: "capacitor",
      schemaMode: "migrate",
      iosLocal: true,
      lanHost: "192.168.50.10",
    },
    assert: [
      hasObserved<ProfileContext, ProfileSetupPlan>("webOrigin", "http://192.168.50.10:5227"),
      profileContains(/MUXIMO_SCHEMA_MODE=migrate/u),
      profileContains(/MUXIMO_MUXIMOD_HOST=192\.168\.50\.10/u),
      profileContains(/MUXIMO_WEB_HOST=192\.168\.50\.10/u),
      profileContains(
        /MUXIMOD_ALLOWED_ORIGINS=http:\/\/127\.0\.0\.1:5227,http:\/\/localhost:5227,http:\/\/192\.168\.50\.10:5227/u,
      ),
      profileOmits(/MUXIMO_TAILSCALE_HOSTNAME=/u),
      hasObserved<ProfileContext, ProfileSetupPlan>(
        "iosContents",
        "// Generated by `mise profile`; rerun it to replace this file.\n" +
          "MUXIMO_WEB_SCHEME = http\n" +
          "MUXIMO_WEB_HOST = 192.168.50.10\n" +
          "MUXIMO_WEB_PORT = 5227\n",
      ),
    ],
  },
  {
    name: "rewrites a localhost profile without adding provider-specific settings",
    input: {
      profileName: "offline",
      templateName: "local",
      templateContents: localRecipe,
      connection: "localhost",
      client: "browser",
      schemaMode: "migrate",
      iosLocal: false,
    },
    assert: [
      hasObserved<ProfileContext, ProfileSetupPlan>("webOrigin", "http://127.0.0.1:5227"),
      profileContains(/MUXIMOD_ALLOWED_ORIGINS=http:\/\/127\.0\.0\.1:5227,http:\/\/localhost:5227/u),
      profileContains(/EXTRA_VALUE=kept/u),
      profileOmits(/MUXIMO_TAILSCALE_HOSTNAME=/u),
      profileOmits(/MUXIMO_MUXIMOD_HOST=/u),
      profileOmits(/MUXIMO_WEB_HOST=/u),
      hasObserved<ProfileContext, ProfileSetupPlan>("iosContents", null),
    ],
  },
  {
    name: "removes Web settings for a daemon-only profile",
    input: {
      profileName: "daemon-only",
      templateName: "local",
      templateContents: localRecipe,
      connection: "localhost",
      client: "none",
      schemaMode: "migrate",
      iosLocal: false,
    },
    assert: [
      hasObserved<ProfileContext, ProfileSetupPlan>("webOrigin", null),
      profileContains(/EXTRA_VALUE=kept/u),
      profileOmits(/MUXIMO_TAILSCALE_HOSTNAME=/u),
      profileOmits(/MUXIMO_MUXIMOD_HOST=/u),
      profileOmits(/MUXIMO_WEB_HOST=/u),
      profileOmits(/MUXIMO_WEB_PORT=/u),
      profileOmits(/MUXIMO_WEB_SERVE_PORT=/u),
      profileOmits(/MUXIMOD_ALLOWED_ORIGINS=/u),
      profileOmits(/capacitor:\/\/localhost/u),
      hasObserved<ProfileContext, ProfileSetupPlan>("iosContents", null),
    ],
  },
  {
    name: "rejects a Tailscale profile without a hostname",
    input: {
      profileName: "missing-host",
      templateName: "local",
      templateContents: localRecipe,
      connection: "tailscale",
      client: "capacitor",
      schemaMode: "migrate",
      iosLocal: false,
    },
    assert: [hasError<ProfileContext, ProfileSetupPlan>({ message: "a Tailscale hostname is required" })],
  },
  {
    name: "rejects a public LAN address",
    input: {
      profileName: "unsafe-lan",
      templateName: "local",
      templateContents: localRecipe,
      connection: "lan",
      client: "browser",
      schemaMode: "migrate",
      iosLocal: false,
      lanHost: "8.8.8.8",
    },
    assert: [hasError<ProfileContext, ProfileSetupPlan>({ message: "LAN connection requires a private IP address" })],
  },
  {
    name: "rejects profile names reserved for tracked recipes",
    input: {
      profileName: "example",
      templateName: "local",
      templateContents: localRecipe,
      connection: "localhost",
      client: "none",
      schemaMode: "migrate",
      iosLocal: false,
    },
    assert: [hasError<ProfileContext, ProfileSetupPlan>({ message: /reserved for \.env\.\*\.example recipes/u })],
  },
  {
    name: "uses the built-in Capacitor origin when the recipe has no Web runtime",
    input: {
      profileName: "staging",
      templateName: "stg",
      templateContents: stagingRecipe,
      connection: "tailscale",
      client: "capacitor",
      schemaMode: "migrate",
      iosLocal: false,
      hostname: "machine.tailnet.ts.net",
    },
    assert: [
      hasObserved<ProfileContext, ProfileSetupPlan>("webOrigin", null),
      profileContains(/MUXIMO_SCHEMA_MODE=migrate/u),
      profileContains(/MUXIMO_TAILSCALE_HOSTNAME=machine\.tailnet\.ts\.net/u),
      profileOmits(/MUXIMO_WEB_PORT=/u),
      profileOmits(/MUXIMO_WEB_SERVE_PORT=/u),
      profileOmits(/MUXIMOD_ALLOWED_ORIGINS=/u),
      hasObserved<ProfileContext, ProfileSetupPlan>("iosContents", null),
    ],
  },
  {
    name: "rejects a browser client for a recipe without Web ports",
    input: {
      profileName: "staging-browser",
      templateName: "stg",
      templateContents: stagingRecipe,
      connection: "tailscale",
      client: "browser",
      schemaMode: "migrate",
      iosLocal: false,
      hostname: "machine.tailnet.ts.net",
    },
    assert: [
      hasError<ProfileContext, ProfileSetupPlan>({
        message: "a browser client requires Web ports in the selected profile recipe",
      }),
    ],
  },
  {
    name: "rejects iOS Local for a bundled Capacitor recipe",
    input: {
      profileName: "staging-local-ios",
      templateName: "stg",
      templateContents: stagingRecipe,
      connection: "tailscale",
      client: "capacitor",
      schemaMode: "migrate",
      iosLocal: true,
      hostname: "machine.tailnet.ts.net",
    },
    assert: [
      hasError<ProfileContext, ProfileSetupPlan>({
        message: "iOS Local configuration requires Web ports in the selected profile recipe",
      }),
    ],
  },
] satisfies readonly OperationCase<"default", ProfileSetupInput, ProfileSetupPlan, ProfileContext>[];

const table: OperationTable<undefined, "default", ProfileSetupInput, ProfileSetupPlan, ProfileContext> = {
  defaultFixture: noFixture(),
  cases,
  execute: (_fixture, input) => createProfileSetupPlan(input),
  observe: (_fixture, result) =>
    result.ok
      ? {
          webOrigin: result.value.webOrigin ?? null,
          profileContents: result.value.profileContents,
          iosContents: result.value.iosContents ?? null,
        }
      : { webOrigin: null, profileContents: null, iosContents: null },
};

describe("profile setup plan", () => {
  runOperationTable(it as unknown as TestRegistrar, table);
});
